apiVersion: v1
kind: Service
metadata:
  name: nightmint-indexer
  namespace: nightmint
  labels:
    app.kubernetes.io/name: nightmint-indexer
    app.kubernetes.io/part-of: nightmint
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nightmint-indexer
  ports:
    - name: http
      port: 80
      targetPort: http
